cc_library(
    name = "seqList",
    hdrs = ["seqList.h"],
)

cc_library(
    name = "binaryTree",
    hdrs = [
      "binaryTreeNode.h",
      "binaryTree.h",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
      ":seqList", 
    ],
)
